// import { CategoryNodeTag } from "@/types/category";

//   export const SKIN_BEAUTY_CATEGORIES: CategoryNodeTag[] = [
//     // { key: "recommend", ko: "추천", en: "Recommend" },
//     {
//       key: "face",
//       ko: "얼굴",
//       en: "Face",
//       children: [
//         {
//           key: "filler",
//           ko: "필러",
//           en: "Filler",
//           children: [
//             { key: "full_face", ko: "풀페이스", en: "Full Face" },
//             { key: "forehead_glabella", ko: "이마/미간", en: "Forehead Glabella" },
//             { key: "nose", ko: "코", en: "Nose" },
//             { key: "lips_mouth_corner", ko: "입술/입꼬리", en: "Lips Mouth Corner" },
//             { key: "eyes", ko: "눈", en: "Eyes" },
//             { key: "chin", ko: "턱", en: "Chin" },
//             { key: "cheek_zygomatic", ko: "볼/광대", en: "Cheek Zygomatic" },
//             { key: "neck", ko: "목", en: "Neck" },
//             { key: "nasolabial_fold", ko: "팔자", en: "Nasolabial Fold" },
//             { key: "temple", ko: "관자놀이", en: "Temple" },
//             { key: "scalp", ko: "두상", en: "Scalp" },
//             { key: "filler_removal", ko: "필러제거", en: "Filler Removal" },
//           ],
//         },
//         {
//           key: "lifting",
//           ko: "리프팅",
//           en: "Lifting",
//           children: [
//             { key: "laser_lifting", ko: "레이저리프팅", en: "Laser Lifting" },
//             { key: "thread_lifting", ko: "실리프팅", en: "Thread Lifting" },
//             { key: "nose_lifting", ko: "코리프팅", en: "Nose Lifting" },
//             { key: "nerve_block_lifting", ko: "신경차단리프팅", en: "Nerve Block Lifting" },
//           ],
//         },
//         {
//           key: "botox",
//           ko: "보톡스",
//           en: "Botox",
//           children: [
//             { key: "full_face", ko: "풀페이스", en: "Full Face" },
//             { key: "chin", ko: "턱", en: "Chin" },
//             { key: "parotid_gland", ko: "침샘", en: "Parotid Gland" },
//             { key: "forehead_glabella", ko: "이마/미간", en: "Forehead Glabella" },
//             { key: "eyes", ko: "눈", en: "Eyes" },
//             { key: "skin", ko: "스킨", en: "Skin" },
//             { key: "lips_mouth_corner", ko: "입술/입꼬리", en: "Lips Mouth Corner" },
//             { key: "gums", ko: "잇몸", en: "Gums" },
//             { key: "hyperhidrosis", ko: "다한증", en: "Hyperhidrosis" },
//             { key: "cheek_zygomatic", ko: "볼/광대", en: "Cheek Zygomatic" },
//             { key: "nose", ko: "코", en: "Nose" },
//             { key: "neck", ko: "목", en: "Neck" },
//             { key: "nasolabial_fold", ko: "팔자", en: "Nasolabial Fold" },
//             { key: "temple", ko: "관자놀이", en: "Temple" },
//           ],
//         },
//         {
//           key: "fat_dissolving_contouring_injection",
//           ko: "지방분해/윤곽주사",
//           en: "Fat Dissolving/Contouring Injection",
//           children: [
//             { key: "full_face", ko: "풀페이스", en: "Full Face" },
//             { key: "cheek_zygomatic", ko: "볼/광대", en: "Cheek Zygomatic" },
//             { key: "chin", ko: "턱", en: "Chin" },
//             { key: "nose", ko: "코", en: "Nose" },
//           ],
//         },
//       ],
//     },
//     {
//       key: "body",
//       ko: "체형",
//       en: "Body",
//       children: [
//         {
//           key: "fat_dissolving_contouring_injection",
//           ko: "지방분해/윤곽주사",
//           en: "Fat Dissolving/Contouring Injection",
//           children: [
//             { key: "abdomen", ko: "복부", en: "Abdomen" },
//             { key: "flank_love_handle", ko: "옆구리/러브핸들", en: "Flank Love Handle" },
//             { key: "arm", ko: "팔", en: "Arm" },
//             { key: "thigh", ko: "허벅지", en: "Thigh" },
//             { key: "knee_calf_ankle", ko: "무릎/종아리/발목", en: "Knee Calf Ankle" },
//             { key: "trapezius_collar_back", ko: "승모근/쇄골/등", en: "Trapezius Collar Back" },
//             { key: "buttock", ko: "엉덩이", en: "Buttock" },
//             { key: "whole_body", ko: "전신", en: "Whole Body" },
//           ],
//         },
//         {
//           key: "diet",
//           ko: "다이어트",
//           en: "Diet",
//           children: [
//             { key: "fat_extraction_injection", ko: "지방추출주사", en: "Fat Extraction Injection" },
//             { key: "carboxytherapy", ko: "카복시테라피", en: "Carboxytherapy" },
//             { key: "diet_program", ko: "다이어트 프로그램", en: "Diet Program" },
//             { key: "cryolipolysis", ko: "냉각지방분해", en: "Cryolipolysis" },
//             { key: "laser_extracorporeal_shockwave", ko: "레이저/체외충격파", en: "Laser Extracorporeal Shockwave" },
//             { key: "cellulite_toning", ko: "셀룰라이트토닝", en: "Cellulite Toning" },
//           ],
//         },
//         {
//           key: "stretch_mark_treatment",
//           ko: "튼살치료",
//           en: "Stretch Mark Treatment",
//           children: [
//             { key: "laser", ko: "레이저", en: "Laser" },
//             { key: "microneedle", ko: "마이크로니들", en: "Microneedle" },
//           ],
//         },
//         {
//           key: "filler",
//           ko: "필러",
//           en: "Filler",
//           children: [
//             { key: "buttock_pelvis", ko: "엉덩이/골반", en: "Buttock Pelvis" },
//             { key: "calf", ko: "종아리", en: "Calf" },
//             { key: "breast", ko: "가슴", en: "Breast" },
//             { key: "filler_removal", ko: "필러제거", en: "Filler Removal" },
//           ],
//         },
//         {
//           key: "lifting",
//           ko: "리프팅",
//           en: "Lifting",
//           children: [
//             { key: "laser_lifting", ko: "레이저리프팅", en: "Laser Lifting" },
//             { key: "thread_lifting", ko: "실리프팅", en: "Thread Lifting" },
//             { key: "nerve_block_lifting", ko: "신경차단리프팅", en: "Nerve Block Lifting" },
//           ],
//         },
//         {
//           key: "botox",
//           ko: "보톡스",
//           en: "Botox",
//           children: [
//             { key: "trapezius_collar", ko: "승모근/쇄골", en: "Trapezius Collar" },
//             { key: "thigh", ko: "허벅지", en: "Thigh" },
//             { key: "calf", ko: "종아리", en: "Calf" },
//             { key: "arm", ko: "팔", en: "Arm" },
//           ],
//         },
//         {
//           key: "body_whitening",
//           ko: "바디미백",
//           en: "Body Whitening",
//           children: [
//             { key: "armpit", ko: "겨드랑이", en: "Armpit" },
//             { key: "elbow", ko: "팔꿈치", en: "Elbow" },
//             { key: "y_zone", ko: "Y존", en: "Y Zone" },
//             { key: "buttock", ko: "엉덩이", en: "Buttock" },
//             { key: "knee", ko: "무릎", en: "Knee" },
//             { key: "elbow_ankle", ko: "팔꿈치/복숭아뼈", en: "Elbow Ankle" },
//             { key: "nipple_areola", ko: "유두/유륜", en: "Nipple Areola" },
//           ],
//         },
//       ],
//     },
//     {
//       key: "skin",
//       ko: "피부",
//       en: "Skin",
//       children: [
//         {
//           key: "elasticity_regeneration",
//           ko: "탄력/재생",
//           en: "Elasticity Regeneration",
//           children: [
//             { key: "skin_booster", ko: "스킨부스터", en: "Skin Booster" },
//             { key: "collagen_booster", ko: "콜라겐부스터", en: "Collagen Booster" },
//             { key: "vitamin_injection_iv", ko: "비타민주사/수액", en: "Vitamin Injection Iv" },
//             { key: "skin_care", ko: "스킨케어", en: "Skin Care" },
//           ],
//         },
//         {
//           key: "acne_pore",
//           ko: "여드름/모공",
//           en: "Acne/Pore",
//           children: [
//             { key: "pore_care", ko: "모공케어", en: "Pore Care" },
//             { key: "acne_extraction", ko: "여드름압출", en: "Acne Extraction" },
//             { key: "acne_scar", ko: "여드름흉터", en: "Acne Scar" },
//             { key: "acne_inflammation", ko: "여드름염증", en: "Acne Inflammation" },
//             { key: "skin_care", ko: "스킨케어", en: "Skin Care" },
//           ],
//         },
//         {
//           key: "whitening_freckle_redness",
//           ko: "미백/잡티/홍조",
//           en: "Whitening/Freckle/Redness",
//           children: [
//             { key: "melasma_freckle", ko: "기미/잡티/주근깨", en: "Melasma Freckle" },
//             { key: "mole_seborrheic_keratosis", ko: "점/검버섯", en: "Mole Seborrheic Keratosis" },
//             { key: "skin_tone_up", ko: "피부톤업", en: "Skin Tone Up" },
//             { key: "dark_circle", ko: "다크서클", en: "Dark Circle" },
//             { key: "redness", ko: "홍조", en: "Redness" },
//             { key: "skin_care", ko: "스킨케어", en: "Skin Care" },
//           ],
//         },
//         {
//           key: "moisturizing_soothing",
//           ko: "보습/진정",
//           en: "Moisturizing/Soothing",
//           children: [
//             { key: "skin_booster", ko: "스킨부스터", en: "Skin Booster" },
//             { key: "vitamin_injection_iv", ko: "비타민주사/수액", en: "Vitamin Injection Iv" },
//             { key: "skin_care", ko: "스킨케어", en: "Skin Care" },
//           ],
//         },
//         {
//           key: "skin_disease",
//           ko: "피부질환",
//           en: "Skin Disease",
//           children: [
//             { key: "atopy", ko: "아토피", en: "Atopy" },
//             { key: "seborrheic_dermatitis", ko: "지루성피부염", en: "Seborrheic Dermatitis" },
//             { key: "bromhidrosis_hyperhidrosis", ko: "액취증/다한증", en: "Bromhidrosis Hyperhidrosis" },
//             { key: "scar_burn", ko: "흉터/화상", en: "Scar Burn" },
//             { key: "wart_corn", ko: "사마귀/티눈", en: "Wart Corn" },
//             { key: "syringoma_milia_skin_tag", ko: "환관종/비립종/쥐젖", en: "Syringoma Milia Skin Tag" },
//             { key: "etc", ko: "기타", en: "Etc" },
//           ],
//         },
//       ],
//     },
//     // {
//     //   key: "dental",
//     //   ko: "치아",
//     //   en: "Dental",
//     //   children: [
//     //     { key: "orthodontics", ko: "치아교정", en: "Orthodontics" },
//     //     { key: "whitening", ko: "치아미백", en: "Whitening" },
//     //     { key: "treatment", ko: "치아치료", en: "Treatment" },
//     //     { key: "gum_care", ko: "잇몸관리", en: "Gum Care" },
//     //   ],
//     // },
//     {
//       key: "scalp",
//       ko: "두피/탈모/제모",
//       en: "Scalp",
//       children: [
//         {
//           key: "scalp_hair_loss_care",
//           ko: "두피/탈모케어",
//           en: "Scalp Hair Loss Care",
//           children: [
//             { key: "scalp_care", ko: "두피케어", en: "Scalp Care" },
//             { key: "scalp_hair_follicle_injection", ko: "두피/모낭주사", en: "Scalp Hair Follicle Injection" },
//             { key: "hair_loss_laser", ko: "탈모레이저", en: "Hair Loss Laser" },
//           ],
//         },
//         {
//           key: "hair_transplant",
//           ko: "모발이식",
//           en: "Hair Transplant",
//           children: [
//             { key: "incision", ko: "절개", en: "Incision" },
//             { key: "non_incision", ko: "비절개", en: "Non Incision" },
//           ],
//         },
//         {
//           key: "laser_hair_removal",
//           ko: "레이저제모",
//           en: "Laser Hair Removal",
//           children: [
//             { key: "face", ko: "얼굴", en: "Face" },
//             { key: "body", ko: "바디", en: "Body" },
//           ],
//         },
//       ],
//     },
//     // { key: "vision", ko: "시력교정", en: "Vision" },
//     // { key: "oriental", ko: "한방", en: "Oriental" },
//     {
//       key: "etc",
//       ko: "기타",
//       en: "Etc",
//       children: [
//         {
//           key: "semi_permanent_makeup",
//           ko: "반영구화장",
//           en: "Semi Permanent Makeup",
//           children: [
//             { key: "eyebrow", ko: "눈썹", en: "Eyebrow" },
//             { key: "eyeliner", ko: "아이라인", en: "Eyeliner" },
//             { key: "lips", ko: "입술", en: "Lips" },
//             { key: "scalp_hairline", ko: "두피/헤어라인", en: "Scalp Hairline" },
//             { key: "nipple_areola", ko: "유두/유륜", en: "Nipple Areola" },
//             { key: "beauty_spot", ko: "미인점", en: "Beauty Spot" },
//             { key: "tattoo_removal", ko: "문신제거", en: "Tattoo Removal" },
//           ],
//         },
//         { key: "female_procedure", ko: "여성시술", en: "Female Procedure" },
//         { key: "post_surgery_care", ko: "성형후관리", en: "Post Surgery Care" },
//         { key: "other_petitskin", ko: "기타쁘띠/피부", en: "Other Petitskin" },
//       ],
//     },
//   ];
  